[pytest]
addopts =
    --browser=chrome
    --alluredir=allureReport
    --clean-alluredir
bdd_features_base_dir = tests/features/
testpaths = tests
markers =
    adminSaaSLogin
    functional
    negative
