[locators]

# Locators of login page
email_XPATH=(By.XPATH, "//*[@id=\"__layout\"]/div/div[2]/div/div/div[1]/div[2]/form/div[1]/input")
password_XPATH=(By.XPATH, "//*[@id=\"__layout\"]/div/div[2]/div/div/div[1]/div[2]/form/div[2]/input")
signInBtn_XPATH=(By.XPATH, "//*[@id=\"__layout\"]/div/div[2]/div/div/div[1]/div[2]/form/div[4]/button")
pleaseWaitText_XPATH=(BY.XPATH, "//p[normalize-space()=\'Please wait...\']")
foldingCube_XPATH=(By.XPATH, "//div[@class=\'sk-folding-cube\']")