[locators]
# Locators of login page
email_XPATH=//*[@id="__layout"]/div/div[2]/div/div/div[1]/div[2]/form/div[1]/input
password_XPATH=//*[@id="__layout"]/div/div[2]/div/div/div[1]/div[2]/form/div[2]/input
signInBtn_XPATH=//*[@id="__layout"]/div/div[2]/div/div/div[1]/div[2]/form/div[4]/button
pleaseWaitText_XPATH=//p[normalize-space()='Please wait...']
foldingCube_XPATH=//div[@class='sk-folding-cube']
loginFail_XPATH=//*[@id="__layout"]/div/div[2]/div/div/div[1]/div[2]/form/p
signUpLink_XPATH=//*[@id="__layout"]/div/div[2]/div/div/div[1]/div[2]/div/a

# Locators of sign up page
signInLink_XPATH=//*[@id="__layout"]/div/div[2]/div/div/div[1]/div[2]/div[1]/a
signUpText_XPATH=//*[@id="__layout"]/div/div[2]/div/div/div[1]/div[2]/div[1]/div
signUpEmail_XPATH=//*[@id="__layout"]/div/div[2]/div/div/div[1]/div[2]/form/div[1]/input
signUpPwd_XPATH=//*[@id="__layout"]/div/div[2]/div/div/div[1]/div[2]/form/div[3]/input
signUpCnfPwd_XPATH=//*[@id="__layout"]/div/div[2]/div/div/div[1]/div[2]/form/div[5]
signUpFName_XPATH=//*[@id="__layout"]/div/div[2]/div/div/div[1]/div[2]/form/div[7]/input
signUpLName_XPATH=//*[@id="__layout"]/div/div[2]/div/div/div[1]/div[2]/form/div[9]/input
signUpCompany_XPATH=//*[@id="__layout"]/div/div[2]/div/div/div[1]/div[2]/form/div[11]/input
signUpCheckbox_XPATH=//*[@id="input-tos"]
signUpBtn_XPATH=//*[@id="signup-button-signup-page"]
signUpSuccess_XPATH=//*[@id="__layout"]/div/div[2]/div/div/div[1]/div[2]/div[2][text()="Sign up to Indee"]
signUpVerifyBtn_XPATH=//*[@id="__layout"]/div/div/div/div[4]/a/button

# Locators of project home page
createNewProjectBtn_XPATH=//*[@id="__layout"]/div/div/div/div[2]/div/div[1]/div/div[1]/a

# Locators of create project page
projectName_XPATH=//*[@id="__layout"]/div/div/div/div[2]/div/div/div[2]/div/div/form/fieldset/div/div[1]/div[2]/input
projectContact_XPATH=//*[@id="__layout"]/div/div/div/div[2]/div/div/div[2]/div/div/form/fieldset/div/div[3]/div[2]/input
projectPoster_XPATH=//*[@id="__layout"]/div/div/div/div[2]/div/div/div[2]/div/div/form/fieldset/div/div[6]/div[2]/div/div/input
projectBanner_XPATH=//*[@id="__layout"]/div/div/div/div[2]/div/div/div[2]/div/div/form/fieldset/div/div[7]/div[2]/div/div/input
projectDesc_XPATH=//*[@id="project-description-html-editor"]/div[1]
projectGenre_XPATH=//*[@id="__layout"]/div/div/div/div[2]/div/div/div[2]/div/div/form/fieldset/div/div[11]/div[2]/div/div/div/div/input
projectEpisodeBox_XPATH=//*[@id="input-kind-of"]
projectCast_XPATH=//*[@id="__layout"]/div/div/div/div[2]/div/div/div[2]/div/div/form/fieldset/div/div[15]/div[2]/div/span/div/div/input[1]
projectRole_XPATH=//*[@id="__layout"]/div/div/div/div[2]/div/div/div[2]/div/div/form/fieldset/div/div[15]/div[2]/div/span/div/div/input[2]
projectCastBtn_XPATH=//*[@id="__layout"]/div/div/div/div[2]/div/div/div[2]/div/div/form/fieldset/div/div[15]/div[2]/button

# Locators of nimad
nimadAccount_XPATH=//*[@id="id_username"]
nimadPassword_XPATH=//*[@id="id_password"]
nimadLoginBtn_XPATH=//*[@id="login-form"]/div[3]/input
nimadEmails_XPATH=//*[@id="result_list"]/tbody/tr
nimadIDs_XPATH=//*[@id="result_list"]/tbody/tr
nimadVerify_XPATH=//*[@id="email_form"]/div/fieldset[2]/div[2]/div/div/div/div/table/tbody/tr[2]/td/div/a
