[locators]
# Locators of login page based on variable extension
email_XPATH=//*[@id="__layout"]/div/div[2]/div/div/div[1]/div[2]/form/div[1]/input
password_XPATH=//*[@id="__layout"]/div/div[2]/div/div/div[1]/div[2]/form/div[2]/input
signInBtn_XPATH=//*[@id="__layout"]/div/div[2]/div/div/div[1]/div[2]/form/div[4]/button
pleaseWaitText_XPATH=//p[normalize-space()='Please wait...']
foldingCube_XPATH=//div[@class='sk-folding-cube']
loginFail_XPATH=//*[@id="__layout"]/div/div[2]/div/div/div[1]/div[2]/form/p